name: practice-cicd
on: workflow_dispatch # Write to trigger the workflow manually
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Steps
        run: echo "This job is related to BUild"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Testing steps
        run: echo "This is job for testing"
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Testing steps
        run: echo "This is job for Deployment"
