name: practice-cicd
# on: workflow_dispatch # Write to trigger the workflow manually
# on: push # On push trigger
on:
  push:
    branches:
      - main
      - develop 
  pull_request:
    types: [opened, synchronize, reopened, closed] 
    branches:
      - main
jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Action Demo Steps
        run: cat index.html
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Steps
        run: |
          echo "This job is related to Build ${{ vars.MY_NAME }}"
          echo "This job is related to Build ${{ secrets.DOCKER_USER_NAME }}"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing steps
        run: echo "This is job for testing ${{ secrets.DOCKER_USER_NAME }}"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment steps
        run: echo "This is job for Deployment ${{ vars.MY_NAME }}"
