name: practice-cicd
on: workflow_dispatch # Write to trigger the workflow manually
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
     - name: Steps
       run: |
         echo "Welcome Ehtsham in the course of COntinuous integration and continuous delivery"
         echo "In this course you will learn Github Actions"
