name: output-demo
on: 
    push:
        branches:
            - main
jobs:
    demo-job:
        runs-on: ubuntu-latest
        steps:
            - name: step 01
              id: step-01
              run: echo "DEMO_OUTPUT=Hello from Step 01" >> $GITHUB_OUTPUT
            - name: step-02
              run: echo "Output from Step 01 ${{ steps.step-01.outputs.DEMO_OUTPUT }}"
            - name: step 03
              if: github.ref == 'refs/heads/main'
              run: echo "This runs only on main branch"
            - name: step 04
              if: github.ref != 'refs/heads/main'
              run: echo "This runs on non-main branches"