name: output-demo
on: 
    push:
        branches:
            - main
jobs:
    demo-job:
        runs-on: ubuntu-latest
        steps:
            - name: step 01
              id: step-01
              run: echo "DEMO_OUTPUT=Hello from Step 01" >> $GITHUB_OUTPUT
            - name: step-02
              run: echo "Output from Step 01 ${{ steps.step-01.outputs.DEMO_OUTPUT }}"
            - name: step 03
              if: github.ref == 'refs/heads/main'
              # github.ref_name directly refer to branch name
              # github.ref directly refer to full ref path
              run: echo "This runs only on main branch"
            - name: step 04
              if: github.ref != 'refs/heads/main'
              run: echo "This runs on non-main branches"
            - name: step 05
              if: github.actor == 'MrEhtsham0' || github.repository == 'https://github.com/MrEhtsham0/CI_CD_Practice.git'
              run: echo "This runs because one of the conditions is true ${{ github.actor }} and ${{ github.repository }}"